<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';

$configurator = new \Nette\Configurator();

$configurator->setTempDirectory(__DIR__ . "/temp");

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
    ->addDirectory(__DIR__ . "../../")
    ->register();

// Create Dependency Injection container from config.neon file
//$configurator->addConfig(__DIR__ . '/config/config.dev.neon');
$container = $configurator->createContainer();

return $container;
